### ISSUE TITLE
Create form view from Survey model

### ISSUE THREAD

**Issue by ianfieldhouse** [edina/crowdsurvey#15]
Once we have successfully modelled survey JSON in Survey and related Field models [#12]  we need to display this information in a ViewController as a series of form items. [Eureka](https://github.com/xmartlabs/Eureka) is a Swift form building framework and so it is suggested that we use this as it is developed by the same development team who created [XLForm](https://github.com/xmartlabs/XLForm) which we had investigated for the work carried out earlier in the Objective-C version of the app.
- [ ] Add form validation [#34]

**Comment by benismobile** [comment]
#21
