### ISSUE TITLE
Enable Bitcode flag has to be turned off to deploy on physical device

### ISSUE THREAD

**Issue by colingor** [edina/crowdsurvey#22]
The Enable Bitcode flag has to be turned off to deploy the code onto a device as the CouchBase library has not been compiled with Bitcode support. See https://github.com/couchbase/couchbase-lite-ios/issues/916 for more detail.

We will turn Bitcode off for the time being so we can get on with development, but we should revisit this and deploy with the bitcode flag on in the future when we've had a chance to look at CouchBase.

**Comment by benismobile** [comment]
putting native app on hold, pending project review
