### ISSUE TITLE
Check if the requested survey is already cached on the device

### ISSUE THREAD

**Issue by ianfieldhouse** [edina/crowdsurvey#28]
When a survey is requested (by launching the app via a custom url or selecting from a list of surveys) a check should be made to see if the requested survey (and it's constituent parts; e.g. images, tiles, etc) already exists on the device

**Comment by ianfieldhouse** [comment]
Currently only check that Survey JSON is downloaded and stored in Couchbase. Work needs to be done to check that constituent part of Survey are downloaded to device. This issue needs work carried out on the server before it can proceed any further.

**Comment by benismobile** [comment]
putting native CrowdSurvey apps on hold for the moment, pending project review
