### ISSUE TITLE
Download the requested survey resources

### ISSUE THREAD

**Issue by ianfieldhouse** [edina/crowdsurvey#30]
When an survey is requested from the server the JSON file describing the survey and it's constituent parts (e.g. images, tiles, etc) should be downloaded and stored on the device.

**Comment by ianfieldhouse** [comment]
Already storing the Survey JSON in Couchbase [#10]. Work can't progress with this issue until work is carried out on server to provide the constituent resources related to a survey.

**Comment by ianfieldhouse** [comment]
Mapbox SDK now supports offline maps so we should try to use this functionality to cache maps from our own Vector Tile server.

**Comment by ianfieldhouse** [comment]
Worth reading with regards to Offline Maps and the MapBox SDK .
- https://github.com/mapbox/mapbox-gl-native/pull/4221
- https://www.mapbox.com/help/mobile-offline/

**Comment by benismobile** [comment]
putting native CrowdSurvey apps on hold for the moment, pending project review
