### ISSUE TITLE
Location field in survey form should use custom field

### ISSUE THREAD

**Issue by ianfieldhouse** [edina/crowdsurvey#57]
The location field is currently just a text field. This should be changed to use a custom location field like the one used in the Eureka Form example project.

**Comment by murrayk** [comment]
The location field is just a textfield in android as well do you have a link to the eureka form example? @ianfieldhouse cheers

**Comment by ianfieldhouse** [comment]
If you download the example project from [xmartlabs/Eureka](https://github.com/xmartlabs/Eureka) you can add the location field to the project as they have a location field defined in their file [CustomCells.swift](https://github.com/xmartlabs/Eureka/blob/master/Example/Example/CustomCells.swift).

I'm not sure we are going to implement the location field this way, however, as our form display ViewController is a modal view so if we segue away from it we don't have a navigation bar to allow us to segue back. I might try and just add a mini map to the top of the form and the user can fine tune their location by panning that and this will update the location field. We still plan to display the lat, lon coords no matter what way we implement this.

**Comment by benismobile** [comment]
putting the native CrowdSurvey apps on hold for the moment
